<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>styl</string>
	</array>
	<key>name</key>
	<string>Stylus</string>
	<key>scopeName</key>
	<string>source.styl</string>
	<key>uuid</key>
	<string>EAB13514-1AFB-435E-B0B6-A44F920DC919</string>
</dict>
</plist>
